version: '3.8'

services:
  backend:
    build:
      context: ./backend
      dockerfile: backend/Dockerfile
    ports:
      - '4000:4000'
    restart: always

  frontend:
    build:
      context: backend
      dockerfile: backend/Dockerfile
    ports:
      - '3000:3000'
    depends_on:
      - backend
    environment:
      NEXT_PUBLIC_BACKEND_URL: http://backend:4000
    restart: always

  nginx:
    image: nginx:latest
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    ports:
      - "80:80"
    depends_on:
      - frontend
      - backend